<?php

function osci_layout_init()
{
    drupal_add_js(array('osci_layout' => array(
    	'viewer_id' => variable_get('osci_layout_viewer_id', 'osci_viewer'),
        'min_column_width' => (int)variable_get('osci_layout_min_column_width', 200),
    	'max_column_width' => (int)variable_get('osci_layout_max_column_width', 300),
    	'gutter_width' => (int)variable_get('osci_layout_gutter_width', '40'),
    	'inner_page_gutter' => array_map("_osci_to_number",explode(",", variable_get('osci_layout_inner_page_gutter', '20,40,20,40'))),
    	'outer_page_gutter' => array_map("_osci_to_number",explode(",", variable_get('osci_layout_outer_page_gutter', '10,10,10,10'))),
    	'min_lines_per_column' => (int)variable_get('osci_layout_min_lines_per_column', 5),
    	'cache_time' => (int)variable_get('osci_layout_cache_time', 86400),
    )), 'setting');
}

function _osci_to_number($v)
{
    return (int)$v;
}

function osci_layout_menu()
{
    $items = array();

    $items['admin/config/user-interface/osci_layout'] = array(
        'title' => 'OSCI Layout settings',
        'description' => 'Configure the OSCI layout module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('osci_layout_admin'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function osci_layout_admin()
{
    $form = array();

    $form['osci_layout_viewer_id'] = array(
        '#type' => 'textfield',
    	'#title' => t('Viewer Id'),
    	'#default_value' => variable_get('osci_layout_viewer_id', 'osci_viewer'),
    	'#description' => t("The HTML Id of the div that will contain the rendered layout."),
    	'#required' => TRUE,
    );

    $form['osci_layout_min_column_width'] = array(
        '#type' => 'textfield',
    	'#title' => t('Minimum Column Width'),
    	'#default_value' => variable_get('osci_layout_min_column_width', 200),
    	'#description' => t("The minimum width allowed for a column (in pixels)."),
    	'#required' => TRUE,
    );

    $form['osci_layout_max_column_width'] = array(
        '#type' => 'textfield',
    	'#title' => t('Maximum Column Width'),
    	'#default_value' => variable_get('osci_layout_max_column_width', 300),
    	'#description' => t("The maximum width allowed for a column (in pixels)."),
    	'#required' => TRUE,
    );

    $form['osci_layout_gutter_width'] = array(
        '#type' => 'textfield',
    	'#title' => t('Gutter Width'),
    	'#default_value' => variable_get('osci_layout_gutter_width', 40),
    	'#description' => t("The width between each column (in pixels)."),
    	'#required' => TRUE,
    );

    $form['osci_layout_inner_page_gutter'] = array(
        '#type' => 'textfield',
    	'#title' => t('Inner Page Gutter'),
    	'#default_value' => variable_get('osci_layout_inner_page_gutter', '20,40,20,40'),
    	'#description' => t("The padding between the page element and the content (in pixels: top, right, bottom, left)."),
    	'#required' => TRUE,
    );

    $form['osci_layout_outer_page_gutter'] = array(
        '#type' => 'textfield',
    	'#title' => t('Outer Page Gutter'),
    	'#default_value' => variable_get('osci_layout_outer_page_gutter', '10,10,10,10'),
    	'#description' => t("The margin between the page element and its container (in pixels: top, right, bottom, left)."),
    	'#required' => TRUE,
    );

    $form['osci_layout_min_lines_per_column'] = array(
        '#type' => 'textfield',
    	'#title' => t('Minimum Lines per column'),
    	'#default_value' => variable_get('osci_layout_min_lines_per_column', 5),
    	'#description' => t("The minimum number of lines of text required to display a column."),
    	'#required' => TRUE,
    );

    $form['osci_layout_cache_time'] = array(
        '#type' => 'textfield',
    	'#title' => t('Cache Lifetime'),
    	'#default_value' => variable_get('osci_layout_cache_time', 86400),
    	'#description' => t("How long to cache the layout for each node (in seconds)."),
    	'#required' => TRUE,
    );

    return system_settings_form($form);
}

?>