<?php

function citation_init() {
    drupal_add_library('system', 'ui.dialog');
    drupal_add_css(drupal_get_path('module', 'citation').'/css/citation.css');
    drupal_add_js(drupal_get_path('module', 'citation').'/js/jquery.osci.citation.js');
}
/*
function citation_node_view($node, $view_mode, $langcode) {
    drupal_add_library('system', 'ui.dialog');
    drupal_add_css(drupal_get_path('module', 'citation').'/css/citation.css');
    drupal_add_js(drupal_get_path('module', 'citation').'/js/citation.js');
    //$node->content['citation_dialog'] = drupal_get_form('citation_dialog');
}
*/

function citation_dialog($form, &$form_state) {
    $form = array();

    $form['#field_type'] = 'osci_body_copy';
    $form['#prefix'] = '<div id="osci-citation-dialog">';
    $form['#suffix'] = '</div>';

    $form['citation'] = array(
        '#type'     => 'textarea',
        '#title'    => t('Citation'),
    );

    $form['submit'] = array(
        '#type'     => 'submit',
        '#value'    => t('Save'),
    );

    return $form;
}
