<?php 

function aic_custom_theme_registry_alter(&$theme_registry) {
    $theme_path = drupal_get_path('module', 'aic_custom');
    $theme_registry['osci_tk_epub_navigation_generate_toc_item_list']['theme path'] = $theme_path;
    $theme_registry['osci_tk_epub_navigation_generate_toc_item_list']['function'] = 'aic_custom_navigation_generate_toc_item_list';

    $theme_registry['osci_tk_epub_navigation_generate_index']['theme path'] = $theme_path;
    $theme_registry['osci_tk_epub_navigation_generate_index']['function'] = 'aic_custom_navigation_generate_index';

    $theme_registry['osci_tk_epub_ncx_generate_navmap']['theme path'] = $theme_path;
    $theme_registry['osci_tk_epub_ncx_generate_navmap']['function'] = 'aic_custom_ncx_generate_navmap';
}

function aic_custom_navigation_generate_toc_item_list(&$vars) {
    $depth = -1; 
    $flag = false;
    $output = ''; 
    foreach ($vars['toc'] as $key => $leaf) {
        $node = node_load($leaf['nid']);

        while ($leaf['depth'] > $depth) {
            $output .= '<ol><li>';
            $flag = false;
            $depth++;
        }    
        while ($leaf['depth'] < $depth) {
            $output .= '</li></ol>';
            $depth--;
        }    
        if ($flag) {
            $output .= '</li><li>';
            $flag = false;
        }    

        if (empty($node->field_active['und']) || (!empty($node->field_active['und']) && $node->field_active['und'][0]['value'])) {
            $link = $vars['for_export'] ? $leaf['filename'] : $leaf['url'];
            $attrs = "data-section_id='{$leaf['nid']}'";
            $attrs .= " data-subtitle='{$leaf['subtitle']}'";
            $attrs .= " data-timestamp='{$leaf['timestamp']}'";
            $attrs .= " data-thumbnail='{$leaf['thumbnail']}'";
            $output .= "<a href='{$link}' {$attrs}>{$leaf['title']}</a>";
        } else {
            $output .= $leaf['title'];
        }

        $flag = true;
    }    
    while ($depth-- > -1) {
        $output .= '</li></ol>';
    }    
    return $output;
}

function aic_custom_navigation_generate_index(&$vars) {
    $list = ''; 
    $output = ''; 
    if (isset($vars['node']->field_nodetree['und']) && is_array($vars['node']->field_nodetree['und'])) {
        foreach ($vars['node']->field_nodetree['und'] as $nodeTreeItem) {
            $target = $nodeTreeItem['target_nid'];
            $section = node_load($target, _osci_tk_utility_retrieve_revision_id_by_timestamp($target, $vars['rev_time']));
            $link = $vars['for_export'] ? _osci_tk_epub_node_content_filename($section->nid) : _osci_tk_epub_node_content_url($section->nid, $vars['rev_time'], $vars['node']->nid);

            $title = $section->title;
            if (isset($section->field_osci_tk_title) && isset($section->field_osci_tk_title['und'][0]['value'])) {
                $title = $section->field_osci_tk_title['und'][0]['value'];
            }    

            if (empty($section->field_active['und']) || (!empty($section->field_active['und']) && $section->field_active['und'][0]['value'])) {
                $list .= "<li><a href='{$link}'>{$title}</a></li>";

                // if section has figures, include them in index
                if (isset($section->field_figure['und']) && count($section->field_figure['und']) > 0) { 
                    for ($i=0; $i < count($section->field_figure['und']); $i++) {
                        $figure = $section->field_figure['und'][$i];
                        $link = $vars['for_export'] ? _osci_tk_epub_node_figure_filename($section->nid, $i) : _osci_tk_epub_node_figure_url($section->nid, $i, $vars['rev_time'], $vars['node']->nid);
                        $list .= "<li><a href='{$link}'>{$title}: Fig. {$i}</a></li>";
                    }
                }
            } else {
                $list .= "<li>{$title}</li>";
            }
        }
    }

    $output = "<nav epub:type='index' id='book-{$vars['node']->nid}-index'>";
    $output .= "<h1>Index</h1>"; // Optional header
    $output .= "<ol>{$list}</ol>"; // The only other element allowed as a child of <nav>
    $output .= "</nav>";
    return $output;
}

function aic_custom_ncx_generate_navmap(&$vars) {
    $output = null;
    if (!is_null($vars['data']['content_nids'])) {
        // Not using templates for performance. Might consider an XML library.
        $output = "<navMap>";
        $count = 0;
        foreach($vars['data']['content_nids'] as $content) {
            $count++;
            $node = node_load($content['nid']);
            
            if (empty($node->field_active['und']) || (!empty($node->field_active['und']) && $node->field_active['und'][0]['value'])) {
                $url = $vars['for_export'] ? $content['filename'] : $content['url'];
                $output .= '<navPoint id="section-' . $content['nid'] . '" playOrder="' . $count . '"><navLabel><text>' . $content['title'] . '</text></navLabel><content src="' . $url . '" /></navPoint>';
            }
        }

        $output .= "</navMap>";
    }

    return $output;
}
