<?php

/**
 * Implementation of hook_menu
 */
function osci_storage_menu() {
    $items = array();

    $items['storage-demo'] = array(
        'title'             => t('localStorage Demo'),
        'page callback'     => 'osci_storage_demo',
        'access arguments'  => array('access content'),
    );

    return $items;
}

function osci_storage_demo() {
    drupal_add_js(drupal_get_path('module', 'osci_storage').'/js/jquery.storage.js');
    return '<a id="getText" href="#">Get Node</a> |
            <a id="clearCache" href="#">Clear Cache</a>
            <br/>
            <div class="stat"></div>
            <div id="returnResult"></div>
    ';
}
