<?php

function osci_citation_node_view($node, $view_mode, $langcode) {
    drupal_add_library('system', 'ui.dialog');
    drupal_add_css(drupal_get_path('module', 'osci_citation').'/css/osci_citation.css');
    drupal_add_js(drupal_get_path('module', 'osci_citation').'/js/osci_citation.js');
    $node->content['citation_dialog'] = drupal_get_form('osci_citation_dialog'); 
}

function osci_citation_dialog($form, &$form_state) {
    $form = array();

    $form['citation'] = array(
        '#type'     => 'textarea',
        '#title'    => t('Citation'),
    );

    $form['submit'] = array(
        '#type'     => 'submit',
        '#value'    => t('Save'),
    );

    return $form;
}
