<?php

/***********************************************************************
 *
 * Drupal Hooks
 *
 */


function osci_filters_init() {
    drupal_add_js(drupal_get_path('module', 'osci_filters').'/js/osci_filters.js', array('weight' => '5'));
}

/**
 * Implementation of hook_filter_info
 */
function osci_filters_filter_info() {
    $filters = array();

    // Footnotes
    $filters['osci_footnote'] = array(
        'title'             => t('Footnote filter'),
        'description'       => t('Allow filters for footnotes'),
        'process callback'  => '_filter_footnote',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_footnote_tips',
    );

    $filters['osci_figure'] = array(
        'title'             => t('Figure filter'),
        'description'       => t('Add references to figure images in content'),
        'process callback'  => '_filter_figure',
        'settings callback' => '_filter_settings',
        'tips callback'     => '_filter_figure_tips',
    );

    return $filters;
}

/**
 * Implementation of hook_wysiwyg_plugin
 */
function osci_filters_wysiwyg_plugin($editor, $version) {
    switch($editor) {
        case 'ckeditor':
/*
            return array(
                'osci_filters' => array(
                    'path'      => drupal_get_path('module', 'osci_filters').'/js/osci_filters.js',
                    'buttons'   => array(
                        'footnote' => t('OSCI - Footnote'),
                    ),
                    'load'      => TRUE,
                ),
            );
*/
    }
}

/**
 * Empty settings function, seems to be required by hook_filter_info
 */
function _filter_settings() {}

/***********************************************************************
 *
 * FOOTNOTE
 *
 */

/**
 * Process callback for filter
 */
function _filter_footnote($text, $filter, $format) {
    $regex = '/\[footnote:(.*?)\]/i';
    return preg_replace_callback($regex, '_process_footnote', $text);
}

/**
 * Regex replace callback
 */
function _process_footnote($text) {
    if (empty($text[1])) return $text[0]; 

    $options = array(
        'fragment'      => $text[1],
        'attributes'    => array(
            'class'     => array('superscript', 'footnote-link'),
        ),
    );
    return l($text[1], $_GET['q'], $options); 
}

/**
 * Tooltip funcion
 */
function _filter_footnote_tips() {
    return t('Insert a footnote with [footnote:ID]');
}


/***********************************************************************
 *
 * FIGURE
 *
 */

function _filter_figure($text, $filter, $format) {
    $regex = '/\[figure:(.*?)\]/i';
    return preg_replace_callback($regex, '_process_figure', $text);
}

function _process_figure($text) {

}

function _filter_figure_tips() {
    return t('Insert a reference to a figure with [figure:ID]');
}
/************** INSERT OTHER FILTER FUNCTIONS HERE ********************/


/***********************************************************************
 *
 * HELPER FUNCTIONS
 *
 */
