<?php

function osci_layout_menu() 
{
    $items = array();

    $items['node/%/reader'] = array(
        'title' => 'Reader',
        'description' => 'Reader layout for book display',
        'page callback' => 'osci_layout_render',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK
    );

    return $items;
}

function osci_layout_render($nid) 
{
    //drupal_add_js('http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js','external');
    drupal_add_js(drupal_get_path('module', 'osci_layout') . '/js/jquery.jswipe-0.1.2.js');
    drupal_add_js("misc/ui/jquery.effects.core.min.js");
    drupal_add_js("misc/ui/jquery.effects.pulsate.min.js");
    drupal_add_js(drupal_get_path('module', 'osci_storage') . '/js/jquery.storage.js');
    drupal_add_js(drupal_get_path('module', 'osci_layout') . '/js/jquery.osci.layout.js');
    drupal_add_js(drupal_get_path('module', 'osci_iip') . '/js/osci_iip_nns.min.js', 'file');
    drupal_add_js(drupal_get_path('module', 'osci_iip') . '/js/osci_iip_polymaps.min.js', 'file');
    drupal_add_js(drupal_get_path('module', 'osci_iip') . '/js/osci_iip.js', 'file');
    drupal_add_css(drupal_get_path('module', 'osci_layout').'/css/osci_layout.css');
    $output = render(drupal_get_form('osci_citation_dialog'));
    $output .= '<div id="osci_viewer_wrapper"><div id="osci_viewer"></div><div id="osci_navigation"></div><div id="osci_reader_content"></div></div>';
    return $output;
}
