<?php

function osci_layout_menu() 
{
    $items = array();

    $items['node/%/reader'] = array(
        'title' => 'Reader',
        'description' => 'Reader layout for book display',
        'page callback' => 'osci_layout_render',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_LOCAL_TASK
    );

    return $items;
}

function osci_layout_render($nid) 
{
    //drupal_add_js('http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js','external');
    drupal_add_js(drupal_get_path('module', 'osci_storage').'/js/jquery.storage.js');
    drupal_add_js(drupal_get_path('module', 'osci_layout').'/js/jquery.osci.layout.js');
    drupal_add_css(drupal_get_path('module', 'osci_layout').'/css/osci_layout.css');
    return '<div id="osci_viewer_wrapper"><div id="osci_viewer"></div><div id="osci_navigation"></div><div id="osci_reader_content"></div></div>';
}
