<?php

function osci_body_copy_menu()
{
    $items = array();

    $items['node/%/bodycopy'] = array(
        'title'             => 'Raw Content',
        'description'       => 'Body copy layout for book display',
        'page callback'     => 'osci_body_copy_render_layout',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'type'              => MENU_CALLBACK
    );

    $items['ajax/figure'] = array(
        'title'             => 'Figure search',
        'page callback'     => 'figure_reference',
        'access arguments'  => array('access content'),
        'type'              => MENU_CALLBACK,
    );

    return $items;
}

function osci_body_copy_theme()
{
    return array(
        'body_copy_field_html5' => array(
            'render element'    => 'element',
            'template'          => 'templates/osci_body_copy_field_html5'
        ),
        'body_copy_footnote' => array(
            'template'  => 'templates/osci_body_copy_footnote',
            'variables' => array(
                'fnId'      => null,
                'fnCopy'    => null
            )
        ),
        'body_copy_node' => array(
            'template'          => 'templates/osci_body_copy_node',
            'render element'    => 'element'
        ),
        'body_copy_footnotes' => array(
            'template'  => 'templates/osci_body_copy_footnotes',
            'variables' => array(
                'footnotes' => array()
            )
        ),
        'body_copy_figure' => array(
            'template'  => 'templates/osci_body_copy_figure',
            'file'      => 'osci_body_copy.templates.inc',
            'variables' => array(
                'figure'            => array(),
                'body_copy_format'  => null,
            )
        ),
        'body_copy_figures' => array(
            'template' => 'templates/osci_body_copy_figures',
            'variables' => array(
                'figures' => array()
            )
        )
    );
}

function osci_body_copy_render_layout($nid)
{
    $node = node_load($nid);
    $elements = node_view($node, 'body_copy');
    $footnotes = array();
    $footnoteOrder = array();
    $footnoteCount = 0;
    $figures = array();
    $figureOrder = array();
    $figureCount = 0;

    $bodyCopyElemetns = array();
    foreach($elements as $k => $v) {
        if (strpos($k, 'field_osci_') === 0) {
            $elements[$k]['#theme'] = 'body_copy_field_html5';
        }
        if (is_array($v) && isset($v['#field_type']) && $v['#field_type'] === 'osci_body_copy') {
            $bodyCopyElements[$k] = $v['#weight'];
        }
    }
    asort($bodyCopyElements);
    
    foreach ($bodyCopyElements as $k => $weight) {
        $v = $elements[$k];
        $elements[$k]['#theme'] = 'body_copy_field_html5';

        $markup = $v[0]['#markup'];
        if (strlen($markup)) {
            $dom = new domDocument;
            $dom->loadHTML($v[0]['#markup']);
            $xpath = new DOMXpath($dom);

            $links = $xpath->query("//a[contains(concat(' ', normalize-space(@class), ' '), ' footnote-link ')]");
            if (!is_null($links)) {
                foreach($links as $link) {
                    $fnId = $link->nodeValue;
                    $originalLinkHtml = $dom->saveXML($link);

                    $link->nodeValue = ++$footnoteCount;
                    $linkHtml = $dom->saveXML($link);
                    $markup = str_replace($originalLinkHtml, $linkHtml, $markup);

                    $footnoteOrder[$footnoteCount] = $fnId;
                }
            }
            $links = $xpath->query("//a[contains(concat(' ', normalize-space(@class), ' '), ' figure-link ')]");
            if (!is_null($links)) {
                foreach($links as $link) {
                    $fId = $link->nodeValue;
                    $originalLinkHtml = $dom->saveXML($link);

                    $link->nodeValue = 'Fig. ' .  ++$figureCount . '';
                    $linkHtml = $dom->saveXML($link);
                    $markup = str_replace($originalLinkHtml, $linkHtml, $markup);

                    $figureOrder[$figureCount] = $fId;
                }
            }
            $elements[$k][0]['#markup'] = $markup;
        }

        $footnotes += $v[0]['osci_footnotes'];
        $figures += $v[0]['osci_figures'];
    }

    if (count($footnotes)) {
        $finalFootnotes = array();
        foreach($footnoteOrder as $k => $fnId) {
            if (isset($footnotes[$fnId])) {
                $finalFootnotes[$k] = array_merge($footnotes[$fnId], array('fnCount' => $k));
            }
        }

        $elements['field_osci_footnotes'] = array(
            '#theme'            => 'body_copy_field_html5',
            '#title'            => 'Footnotes',
            '#weight'           => 999,
            '#label_display'    => 'inline',
            '#field_type'       => 'osci_body_copy',
            '#field_name'       => 'field_osci_footnotes',
            '#attributes'        => array('class' => array('osci_column_break')),
            0 => array(
                '#markup' => theme('body_copy_footnotes', array('footnotes' => $finalFootnotes))
            ),
        );
    }

    if (count($figures)) {
        $finalFigures = array();
        foreach($figureOrder as $k => $fId) {
            if (isset($figures[$fId])) {
                $finalFigures[$k] = array_merge($figures[$fId], array('figCount' => $k));
                $finalFigures[$k]['caption'] = $finalFigures[$k]['caption']; 
            }
        }

        $elements['field_osci_figures'] = array(
            '#theme'            => 'body_copy_field_html5',
            '#title'            => 'Figures',
            '#weight'           => 1000,
            '#label_display'    => 'inline',
            '#field_type'       => 'osci_body_copy',
            '#field_name'       => 'field_osci_figures',
            0 => array(
                '#markup' => theme('body_copy_figures', array('figures' => $finalFigures))
            ),
        );
    }

    $elements['#theme'] = 'body_copy_node';
    unset($elements['#pre_render']);

    print render($elements);
//    return render($elements);
}

function osci_body_copy_entity_info_alter(&$entity_info) 
{
    $entity_info['node']['view modes']['body_copy'] = array(
        'label'             => t('Body Copy'),
        'custom settings'   => TRUE,
    );
}

function osci_body_copy_field_info()
{
    return array(
        'osci_body_copy' => array(
            'label'             => t('Body Copy'),
            'description'       => t('Includes text area for body copy and multi-value field for footnotes & figures'),
            'default_widget'    => 'osci_body_copy_widget',
            'default_formatter' => 'osci_body_copy_formatter'
        )
    );
}

function osci_body_copy_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items)
{
    if ($field['type'] === 'osci_body_copy') {
        $items[0]['footnote_index']     = (int)$items[0]['footnotes']['footnote_index'];
        $items[0]['body_copy_format']   = $items[0]['body_copy']['format'];
        $items[0]['body_copy']          = trim($items[0]['body_copy']['value']);
        $items[0]['figure_index']       = (int)$items[0]['figures']['figure_index'];

        $finalFootnotes = array();
        if (is_array($_POST[$field['field_name']]['und'][0]['footnotes'])) {
            $footnotes = $_POST[$field['field_name']]['und'][0]['footnotes'];
            foreach($footnotes as $id => $footnote) { 
                $uid = substr($field['field_name'], 6) . '_fn_' . $entity->nid . '_' . $id;
                if (empty($footnote) || $id == 'footnote_index' || $id == 'footnote-blank') {
                    continue;
                }
                $finalFootnotes[$uid] = $footnote;
            }
        }
        $items[0]['footnotes'] = serialize($finalFootnotes);

        $finalFigures = array();
        if (is_array($_POST[$field['field_name']]['und'][0]['figures'])) {
            $figures = $_POST[$field['field_name']]['und'][0]['figures'];
            foreach($figures as $id => $figure) {
                $uid = substr($field['field_name'], 6) . '_fig_' . $entity->nid . '_' . $id;
                if (empty($figure['figure_reference']) || $id == 'figure_index' || $id == 'figure-blank') {
                    continue;
                }
                $finalFigures[$uid] = $figure;
            }
        }
        $items[0]['figures'] = serialize($finalFigures);
    }
}

function osci_body_copy_field_is_empty($item, $field)
{
    $return = false;

    if (empty($item['body_copy'])) {
        $return = true;
    }

    return $return;
}

/***********************************************************************
 *  Field Type API: Formatter
 **********************************************************************/

function osci_body_copy_field_formatter_info()
{
    return array(
        'osci_body_copy_formatter' => array(
            'label' => t('Body Copy View'),
            'field types' => array('osci_body_copy')
        ),
        'osci_body_copy_formatter_html5' => array(
            'label' => t('Body Copy HTML5'),
            'field types' => array('osci_body_copy')
        ),
        'osci_text_field_formatter_html5' => array(
            'label' => t('Text Field HTML5'),
            'field types' => array('text', 'text_long')
        )
    );
}

function osci_body_copy_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items)
{
    if ($field['type'] == 'osci_body_copy') {
        foreach($items as $nid => $fields) {
            foreach($fields as $delta => $item) {
                if (isset($item['footnotes'])) {
                    $items[$nid][$delta]['footnotes'] = unserialize($item['footnotes']);
                }

                if (isset($item['figures'])) {
                    $figures = unserialize($item['figures']);

                    foreach($figures as $id => $figure) {
                        $figures[$id]['id'] = $id;
                        $figures[$id]['format'] = $item['body_copy_format'];
                    }
                    $items[$nid][$delta]['figures'] = $figures;
                }
            }
        }
    }
}

function osci_body_copy_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display)
{
    $element = array();

    switch ($display['type']) {
        case 'osci_text_field_formatter_html5':
            foreach($items as $delta => $item) {
                $element[$delta] = array(
                    '#markup' => '<div>' . $item['value'] . '</div>',
                    '#theme'  => 'body_copy_field_html5',
                );
            }
            break;
        case 'osci_body_copy_formatter':
            $rendered_figures = array();

            foreach($items as $delta => $item) {
                $markup = check_markup($item['body_copy'], $item['body_copy_format']);

                $footnotes = $item['footnotes'];
                // Add anchor tags
                if (is_array($footnotes)) {
                    foreach($footnotes as $id => $footnote) {
                        $footnotes[$id] = theme('body_copy_footnote', array('fnId' => $id, 'fnCopy' => check_markup($footnote, $item['body_copy_format'])));
                    }
                }
                $markup .= theme_item_list(array('items' => $footnotes, 'title' => 'Footnotes', 'type' => 'ol', 'attributes' => array()));

                $figures = $item['figures'];
                if (is_array($figures)) {
                    foreach ($figures as $figure) {
                        $rendered_figures[] = theme('body_copy_figure', array('figure' => $figure));
                    }
                }
                $markup .= theme('item_list', array('items' => $rendered_figures, 'title' => t('Figures'), 'type' => 'ol'));

                $element[$delta]['#markup'] = $markup;
            }
            break;
        case 'osci_body_copy_formatter_html5':
            foreach($items as $delta => $item) {
                $markup = check_markup($item['body_copy'], $item['body_copy_format']);
 
                $footnotes = $item['footnotes'];
                // Add anchor tags
                if (is_array($footnotes)) {
                    foreach($footnotes as $id => $footnote) {
                        $footnotes[$id] = array('fnId' => $id, 'fnCopy' => check_markup($footnote, $item['body_copy_format']));
                    }
                }

                $figures = $item['figures'];

                $element[$delta] = array(
                    '#markup' => $markup,
                    '#theme' => 'body_copy_field_html5',
                    'osci_footnotes' => $footnotes,
                    'osci_figures' => $figures
                );
            }
            break;
    }

    return $element;
}

/**************************************************************************
 * Field Type API: Widget
 **************************************************************************/

function osci_body_copy_field_widget_info()
{

    return array(
        'osci_body_copy_widget' => array(
            'label' => t('Body copy with footnotes & figures'),
            'field types' => array('osci_body_copy'),
            'settings' => array('body_copy_rows' => 5, 'footnote_rows' => 3, 'figure_caption_rows' => 3),
            'behaviors' => array('default value' => FIELD_BEHAVIOR_NONE)
        )
    );
}

function osci_body_copy_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element)
{
    drupal_add_library('system', 'ui.tabs');

    $footnoteCount = isset($items[$delta]['footnote_index']) ? $items[$delta]['footnote_index'] : 0;
    $footnoteCount = $footnoteCount ? $footnoteCount : 0;

    $figureCount = isset($items[$delta]['figure_index']) ? $items[$delta]['figure_index'] : 0;
    $figureCount = $figureCount ? $figureCount : 0;

    $bodyCopy = array(
        '#type' => 'fieldset',
        '#attached' => array(
            'js' => array(
                base_path() . 'sites/all/libraries/ckeditor/adapters/jquery.js',
                drupal_get_path('module', 'osci_body_copy') . '/js/body_copy_field.js',
            ),
        ),
        'body_copy' => array(
            '#type' => 'text_format',
            '#base_type' => 'textarea',
            '#default_value' => isset($items[$delta]['body_copy']) ? $items[$delta]['body_copy'] : NULL,
            '#rows' => $instance['widget']['settings']['body_copy_rows'],
            '#format' => null,
        ),
        'footnotes' => array(
            '#type' => 'fieldset',
            '#attributes' => array('class' => array('footnotes-wrapper')),
            '#title' => t('Footnotes'),
            'footnote_index' => array(
                '#type' => 'hidden',
                '#default_value' => $footnoteCount
            ),
        ),
        'figures' => array(
            '#type' => 'fieldset',
            '#attributes' => array('class' => array('figures-wrapper')),
            '#title' => t('Figures'),
            'figure_index' => array(
                '#type' => 'hidden',
                '#default_value' => $figureCount,
                '#weight' => -100
            ),
        )
    );

    $footnotes = array('footnote_blank' => '');
    $loadnotes = (isset($items[$delta]['footnotes']) && !is_array($items[$delta]['footnotes'])) ? unserialize($items[$delta]['footnotes']) : array();
    $footnotes += $loadnotes ? $loadnotes : array();
 
    $bodyCopy['footnotes']['add_another'] = array(
        '#markup' => '<a href="#" class="footnote-add-another">Add Footnote</a>',
        '#weight' => -1,
    );

    $fieldName = substr($field['field_name'], 6);
    $nid = $form['nid']['#value'];

    $fnList = array();
    foreach ($footnotes as $id => $footnote) {
        if ($id !== 'footnote_blank') {
            $id = substr($id, strrpos($id, '_') + 1); 
        }
        $fnId = $fieldName . '_fn_' . $nid . '_' . $id;
        $class = ($id == 1) ? 'footnote first' : 'footnote';
        $bodyCopy['footnotes'][$id] = array(
            '#title' => $id . ' <span>(' . $fnId . ')</span>',
            '#type' => 'textarea',
            '#default_value' => $footnote,
            '#rows' => $instance['widget']['settings']['footnote_rows'],
            '#attributes' => array('class' => array($class)),
            '#prefix' => '<div id="' . $fnId . '" class="footnote-wrapper" data-fnprefix="' . $fieldName . '_fn_' . $nid . '_">',
            '#suffix' => '</div>',
            '#weight' => $id,
        );

        $fnList[] = '<li><a href="#' . $fnId . '">' . $id . '</a></li>';
    }
    
    $bodyCopy['footnotes']['footnote_list'] = array(
        '#markup' => '<ul>' . implode("\n", $fnList) . '</ul>',
        '#weight' => 0
    );

    $figures = array('figure_blank' => '');
    $loadFigures = isset($items[$delta]['figures']) ? unserialize($items[$delta]['figures']) : array();
    $figures += $loadFigures ? $loadFigures : array();

    $bodyCopy['figures']['add_another'] = array(
        '#markup' => '<a href="#" class="figure-add-another">Add Figure</a>',
        '#weight' => -1,
    );

    $figureList = array();
    foreach($figures as $id => $figure) {
        if ($id !== 'figure_blank') {
            $id = substr($id, strrpos($id, '_') + 1);
    	}
        $figId = $fieldName . '_fig_' . $nid . '_' . $id;
        $class = ($id == 1) ? 'figure first' : 'figure';
        $bodyCopy['figures'][$id] = array(
            '#title'        => $id . ' <span>(' . $figId . ')</span>',
            '#type'         => 'fieldset',
            '#attributes'   => array('class' => array($class)),
            '#prefix'       => '<div id="' . $figId . '" data-figprefix="' . $fieldName . '_fig_' . $nid . '_">',
            '#suffix'      => '</div>',
            '#weight'       => $id,
            '#tree'         => true,
            'figure_id'     => array(
                '#markup'   => '<div class="figure_identifier">' . $id . ' <span>(' . $figId . ')</span> </div>'
            ),
            'figure_reference' => array(
                '#title'                => t('Figure Reference'),
                '#description'          => t('The node id of the media that this figure should display.'),
                '#type'                 => 'textfield',
                '#autocomplete_path'    => 'ajax/figure',
                '#default_value'        => isset($figure['figure_reference']) ? $figure['figure_reference'] : '',
            ),
            'caption' => array(
                '#title'            => t('Caption'),
                '#description'      => t('The caption text to associate with this figure'),
                '#type'             => 'textarea',
                '#default_value'    => isset($figure['caption']) ? $figure['caption'] : '',
                '#rows'             => $instance['widget']['settings']['figure_caption_rows']
            ),
            'position' => array(
                '#title'            => t('Position'),
                '#description'      => t('A hint on how to place the figure on a page.'),
                '#type'             => 'select',
                '#default_value'    => isset($figure['position']) ? $figure['position'] : 't',
                '#options'          => array(
                    't'     => 'top',
                    'b'     => 'bottom',
                    'tl'    => 'top left',
                    'tr'    => 'top right',
                    'bl'    => 'bottom left',
                    'br'    => 'bottom right',
                    'p'     => 'full page'
                )
            ),
            'columns' => array(
                '#title'            => t('Columns'),
                '#type'             => 'textfield',
                '#default_value'    => isset($figure['columns']) ? $figure['columns'] : '',
                '#description'      => t('A hint of how many columns the figure should span on a page. This can be either a number (1 or greater) or a percentage (0%-100%).')
            )
        );

        $figureList[] = '<li><a href="#' . $figId . '">' . $id . '</a></li>';
    }

    $bodyCopy['figures']['figure_list'] = array(
        '#markup' => '<ul>' . implode("\n", $figureList) . '</ul>',
        '#weight' => 0
    );

    return $element + $bodyCopy;
}

/**
 * Implements hook_field_widget_settings_form().
 */
function osci_body_copy_field_widget_settings_form($field, $instance) 
{
    $widget = $instance['widget'];
    $settings = $widget['settings'];

    $form['body_copy_rows'] = array(
        '#type' => 'textfield',
        '#title' => t('Body Copy Rows'),
        '#description' => t('The number of rows to use for the Body Copy textarea.'),
        '#default_value' => $settings['body_copy_rows'],
        '#required' => TRUE,
        '#element_validate' => array('_element_validate_integer_positive')
    );

    $form['footnote_rows'] = array(
        '#type' => 'textfield',
        '#title' => t('Footnote Rows'),
        '#description' => t('The number of rows to use for the Footnote textarea.'),
        '#default_value' => $settings['footnote_rows'],
        '#required' => TRUE,
        '#element_validate' => array('_element_validate_integer_positive')
    );

    $form['figure_caption_rows'] = array(
        '#type' => 'textfield',
        '#title' => t('Figure Caption Rows'),
        '#description' => t('The number of rows to use for the Figure caption textarea.'),
        '#default_value' => $settings['figure_caption_rows'],
        '#required' => TRUE,
        '#element_validate' => array('_element_validate_integer_positive')
    );

    return $form;
}

function figure_reference($args) {
    $figs = db_select('node', 'n')
        ->fields('n', array('title', 'nid'))
        ->condition('type', 'image')
        ->condition('status', 1)
        ->condition('title', '%'.db_like($args).'%', 'LIKE')
        ->orderBy('created', DESC)
        ->addTag('node_access')
        ->range(0, 10)
        ->execute();
    foreach($figs as $result) {
        $matches[$result->nid] = $result->title;
    }
    return drupal_json_output($matches);
}
?>
